apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - model-download-job.yaml
  - servingruntime.yaml
  - inferenceservice.yaml
  - external-model.yaml
  - model-ref.yaml
  - subscription.yaml
  - auth-policy.yaml
  - metrics-service.yaml
  - prometheus-rule.yaml
