apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../base/isaac-sim/
  - ../../base/models/dreamzero/
  - ../../base/models/cosmos3-nano/
  - ../../base/models/pi05/

patches:
  - path: playground-ros2-config.yaml
