extends: default

rules:
  line-length:
    max: 200
  indentation:
    spaces: 2
    indent-sequences: whatever
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
  document-start: disable
