apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: redhat-ods-applications
  labels:
    app: physical-ai-studio-backend
spec:
  selector:
    app: physical-ai-studio-backend
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
