apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: robotics-playground-rerun-web
  namespace: redhat-ods-applications
  annotations:
    haproxy.router.openshift.io/timeout: 3600s
spec:
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: robotics-playground-ui
  port:
    targetPort: http-mf
  path: /rerun
