apiVersion: feast.dev/v1
kind: FeatureStore
metadata:
  name: feature-store
  namespace: physical-ai
  labels:
    feature-store-ui: enabled
spec:
  feastProject: physical_ai
  services:
    onlineStore:
      persistence:
        file:
          pvc:
            create:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi
            mountPath: /data/online
    offlineStore:
      persistence:
        file:
          pvc:
            create:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
            mountPath: /data/offline
    registry:
      local:
        server:
          restAPI: true
        persistence:
          file:
            pvc:
              create:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 5Gi
              mountPath: /data/registry
