apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: maas-proxy-upstream-tls
  namespace: openshift-ingress
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      cluster:
        service: maas-proxy.physical-ai-models.svc.cluster.local
    patch:
      operation: MERGE
      value:
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
            sni: maas-proxy.physical-ai-models.svc.cluster.local
            common_tls_context:
              validation_context:
                trusted_ca:
                  filename: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
                match_typed_subject_alt_names:
                - san_type: DNS
                  matcher:
                    exact: maas-proxy.physical-ai-models.svc.cluster.local
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: maas-default-gateway
