apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen25-cpu-model-cache
  namespace: physical-ai-models
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3-csi
