apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
spec:
  strategy:
    type: Recreate
  template:
    spec:
      serviceAccountName: simulator
      securityContext:
        runAsUser: 1234
      nodeSelector:
        gpu-pool-size: large
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      containers:
        - name: isaac-lab
        - name: zenoh-bridge
