apiVersion: datasciencecluster.opendatahub.io/v2
kind: DataScienceCluster
metadata:
  name: default-dsc
spec:
  components:
    kserve:
      managementState: Managed
      rawDeploymentServiceConfig: Headed
      modelsAsService:
        managementState: Managed
    modelregistry:
      managementState: Managed
    dashboard:
      managementState: Managed
    workbenches:
      managementState: Managed
    aipipelines:
      managementState: Managed
    trustyai:
      managementState: Managed
    feastoperator:
      managementState: Managed
    mlflowoperator:
      managementState: Managed
    llamastackoperator:
      managementState: Managed
