apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - dsc-patch.yaml
  - dashboard/
  - maas/
  - maas-proxy.yaml
  - maas-proxy-allowlist.yaml
  - mlflow/
  - models/
  - model-catalog/
