apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - maas/
  - models/

patches:
  - path: dsc-patch.yaml
    target:
      group: datasciencecluster.opendatahub.io
      version: v2
      kind: DataScienceCluster
      name: default-dsc
