apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - dsc-patch.yaml
  - dashboard/
  - feature-store/
  - maas/
  - mlflow/
  - models/
  - model-catalog/
  - pipelines/
  - robotics-playground/
  - robotics-playground-backend/
