apiVersion: v1
kind: Namespace
metadata:
  name: physical-ai
---
apiVersion: v1
kind: Namespace
metadata:
  name: physical-ai-models
---
apiVersion: v1
kind: Namespace
metadata:
  name: models-as-a-service
