apiVersion: v1
kind: Namespace
metadata:
  name: physical-ai
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/feast: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: physical-ai-models
---
apiVersion: v1
kind: Namespace
metadata:
  name: models-as-a-service
