apiVersion: v1
kind: Service
metadata:
  name: cosmos3-nano-metrics
  namespace: physical-ai-models
  labels:
    monitoring.opendatahub.io/scrape: "true"
    name: cosmos3-nano-metrics
spec:
  ports:
  - name: vllm-omni-runtime-metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    serving.kserve.io/inferenceservice: cosmos3-nano
  type: ClusterIP
