apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # yamllint disable-next-line rule:line-length
  - https://github.com/redhat-et/robotics-playground//deploy/kustomize/robotics-playground?ref=main
  - route.yaml
  - route-rerun-grpc.yaml

namespace: physical-ai

patches:
  - path: patches/deployment-env.yaml
