apiVersion: v1
kind: Service
metadata:
  name: pi05-metrics
  namespace: physical-ai-models
  labels:
    monitoring.opendatahub.io/scrape: "true"
    name: pi05-metrics
spec:
  ports:
  - name: openpi-runtime-metrics
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    serving.kserve.io/inferenceservice: pi05
  type: ClusterIP
