apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pi05-triton-cache
  namespace: physical-ai-models
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3-csi
