apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/redhat-et/robotics-playground//deploy/kustomize/isaac-lab?ref=main
  - serviceaccount.yaml
  - scc-rolebinding.yaml

namespace: physical-ai

patches:
  - path: openshift-patches.yaml
