apiVersion: apps/v1
kind: Deployment
metadata:
  name: isaac-lab
spec:
  template:
    spec:
      serviceAccountName: isaac-lab
      securityContext:
        runAsUser: 1234
      nodeSelector:
        nvidia.com/gpu.product: NVIDIA-L40S
      containers:
        - name: isaac-lab
          env:
            - name: ROS_DISCOVERY_SERVER
              value: fastdds-discovery:11811
