apiVersion: apps/v1
kind: Deployment
metadata:
  name: isaac-lab
spec:
  strategy:
    type: Recreate
  template:
    spec:
      serviceAccountName: isaac-lab
      securityContext:
        runAsUser: 1234
      nodeSelector:
        nvidia.com/gpu.product: NVIDIA-L40S
      containers:
        - name: isaac-lab
        - name: zenoh-bridge
