apiVersion: apps/v1
kind: Deployment
metadata:
  name: isaac-lab
spec:
  strategy:
    type: Recreate
  template:
    spec:
      serviceAccountName: isaac-lab
      securityContext:
        runAsUser: 1234
      nodeSelector:
        nvidia.com/gpu.product: NVIDIA-L40S
      containers:
        - name: isaac-lab
          env:
            - name: ROS_DISCOVERY_SERVER
              value: fastdds-discovery:11811
          volumeMounts:
            - name: fastdds-config
              mountPath: /workspace/isaaclab/docker/.ros/fastdds.xml
              subPath: fastdds-client.xml
              readOnly: true
      volumes:
        - name: fastdds-config
          configMap:
            name: fastdds-client-config
